version: "3.2"

###############################################################################
########################## TEST ENVIRONMENT SCRIPT ############################
###############################################################################

services:
    frontend-events:
        image: node:21.2.0
        container_name: portifolio
        working_dir: /home/node/app
        volumes:
            - /home/github/Portifolio/:/home/node/app
        command: bash -c "npm install -g pnpm && pnpm install && pnpm build && PORT=3005 pnpm start"
        restart: always
        networks:
            dev:
                ipv4_address: 172.20.0.12
        ports:
            - 80:3005

volumes:
    portainer_data:

networks:
    dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
